export interface EmployeeProfile {
  id: string;
  page: number;
  imageFilename: string;
  imageUrl: string;
  name: string;
  jobCategory: string;
  experience: string;
  gender: string;
  timing: string;
  salary?: string;
}

const BASE_IMAGE_URL = 'https://www.anydomestichelp.com/images/';

function buildImageUrl(filename: string): string {
  return `${BASE_IMAGE_URL}${encodeURIComponent(filename)}`;
}

export const EMPLOYEE_PROFILES: EmployeeProfile[] = [
  {
    id: 'p1-1',
    page: 1,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Priya S.',
    jobCategory: 'Nurse',
    experience: '8 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (8am)',
    salary: '₹35,000',
  },
  {
    id: 'p1-2',
    page: 1,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Anjali R.',
    jobCategory: 'Babysitter',
    experience: '4 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time (Flexible)',
    salary: '₹18,000',
  },
  {
    id: 'p1-3',
    page: 1,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Sunita Devi',
    jobCategory: 'Housemaid',
    experience: '12 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (Live-in)',
    salary: '₹22,000',
  },
  {
    id: 'p1-4',
    page: 1,
    imageFilename: 'small_family.jpg',
    imageUrl: buildImageUrl('small_family.jpg'),
    name: 'Rahul M.',
    jobCategory: 'Nurse',
    experience: '6 Yrs Exp',
    gender: 'Male',
    timing: 'Full Time (Night)',
    salary: '₹28,000',
  },
  {
    id: 'p1-5',
    page: 1,
    imageFilename: 'images (7).jpg',
    imageUrl: buildImageUrl('images (7).jpg'),
    name: 'Geeta Kapoor',
    jobCategory: 'Babysitter',
    experience: '20 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹24,000',
  },
  {
    id: 'p2-1',
    page: 2,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Meena Kumari',
    jobCategory: 'Cook',
    experience: '6 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time (4 Hrs)',
    salary: '₹15,000',
  },
  {
    id: 'p2-2',
    page: 2,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Lakshmi P.',
    jobCategory: 'Housemaid',
    experience: '8 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹18,000',
  },
  {
    id: 'p2-3',
    page: 2,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Sushila B.',
    jobCategory: 'Nanny',
    experience: '3 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (24 Hrs)',
    salary: '₹20,000',
  },
  {
    id: 'p2-4',
    page: 2,
    imageFilename: 'small_family.jpg',
    imageUrl: buildImageUrl('small_family.jpg'),
    name: 'Deepak S.',
    jobCategory: 'Driver',
    experience: '10 Yrs Exp',
    gender: 'Male',
    timing: 'Full Time',
    salary: '₹22,000',
  },
  {
    id: 'p2-5',
    page: 2,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Kamla Devi',
    jobCategory: 'Elderly Care',
    experience: '5 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (Live-in)',
    salary: '₹25,000',
  },
  {
    id: 'p2-6',
    page: 2,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Rita G.',
    jobCategory: 'Cook',
    experience: '7 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time (8 Hrs)',
    salary: '₹16,000',
  },
  {
    id: 'p2-7',
    page: 2,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Pushpa T.',
    jobCategory: 'Babysitter',
    experience: '2 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time',
    salary: '₹12,000',
  },
  {
    id: 'p3-1',
    page: 3,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Asha K.',
    jobCategory: 'Nurse',
    experience: '4 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹30,000',
  },
  {
    id: 'p3-2',
    page: 3,
    imageFilename: 'small_family.jpg',
    imageUrl: buildImageUrl('small_family.jpg'),
    name: 'Vikram S.',
    jobCategory: 'Office Boy',
    experience: '3 Yrs Exp',
    gender: 'Male',
    timing: 'Full Time (8 Hrs)',
    salary: '₹14,000',
  },
  {
    id: 'p3-3',
    page: 3,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Savita M.',
    jobCategory: 'Housemaid',
    experience: '9 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹20,000',
  },
  {
    id: 'p3-4',
    page: 3,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Rekha D.',
    jobCategory: 'Cook',
    experience: '15 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time (4 Hrs)',
    salary: '₹18,000',
  },
  {
    id: 'p3-5',
    page: 3,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Parvati N.',
    jobCategory: 'Japa Maid',
    experience: '6 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (24 Hrs)',
    salary: '₹28,000',
  },
  {
    id: 'p3-6',
    page: 3,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Bhagwati S.',
    jobCategory: 'Elderly Care',
    experience: '8 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (Live-in)',
    salary: '₹26,000',
  },
  {
    id: 'p3-7',
    page: 3,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Nirmala B.',
    jobCategory: 'Babysitter',
    experience: '5 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹16,000',
  },
  {
    id: 'p4-1',
    page: 4,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Renu K.',
    jobCategory: 'Patient Care',
    experience: '7 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (Night)',
    salary: '₹32,000',
  },
  {
    id: 'p4-2',
    page: 4,
    imageFilename: 'small_family.jpg',
    imageUrl: buildImageUrl('small_family.jpg'),
    name: 'Suresh P.',
    jobCategory: 'Driver',
    experience: '12 Yrs Exp',
    gender: 'Male',
    timing: 'Full Time',
    salary: '₹20,000',
  },
  {
    id: 'p4-3',
    page: 4,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Anita R.',
    jobCategory: 'Cook',
    experience: '10 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time (8 Hrs)',
    salary: '₹17,000',
  },
  {
    id: 'p4-4',
    page: 4,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Shanti D.',
    jobCategory: 'Housemaid',
    experience: '6 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹15,000',
  },
  {
    id: 'p4-5',
    page: 4,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Kavita M.',
    jobCategory: 'Nanny',
    experience: '8 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (24 Hrs)',
    salary: '₹22,000',
  },
  {
    id: 'p4-6',
    page: 4,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Saroj W.',
    jobCategory: 'Home Tuition',
    experience: '4 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time (4 Hrs)',
    salary: '₹20,000',
  },
  {
    id: 'p4-7',
    page: 4,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Lata J.',
    jobCategory: 'Babysitter',
    experience: '3 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹14,000',
  },
  {
    id: 'p5-1',
    page: 5,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Manju S.',
    jobCategory: 'Nurse',
    experience: '10 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹35,000',
  },
  {
    id: 'p5-2',
    page: 5,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Usha T.',
    jobCategory: 'Cook',
    experience: '14 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (8 Hrs)',
    salary: '₹19,000',
  },
  {
    id: 'p5-3',
    page: 5,
    imageFilename: 'small_family.jpg',
    imageUrl: buildImageUrl('small_family.jpg'),
    name: 'Ramesh K.',
    jobCategory: 'Office Boy',
    experience: '5 Yrs Exp',
    gender: 'Male',
    timing: 'Full Time',
    salary: '₹16,000',
  },
  {
    id: 'p5-4',
    page: 5,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Indira P.',
    jobCategory: 'Elderly Care',
    experience: '7 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (Live-in)',
    salary: '₹28,000',
  },
  {
    id: 'p5-5',
    page: 5,
    imageFilename: 'img30.jpg',
    imageUrl: buildImageUrl('img30.jpg'),
    name: 'Sudha R.',
    jobCategory: 'Housemaid',
    experience: '11 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time',
    salary: '₹21,000',
  },
  {
    id: 'p5-6',
    page: 5,
    imageFilename: 'img32.jpg',
    imageUrl: buildImageUrl('img32.jpg'),
    name: 'Preeti V.',
    jobCategory: 'Babysitter',
    experience: '2 Yrs Exp',
    gender: 'Female',
    timing: 'Part Time',
    salary: '₹13,000',
  },
  {
    id: 'p5-7',
    page: 5,
    imageFilename: 'img33.jpg',
    imageUrl: buildImageUrl('img33.jpg'),
    name: 'Kanta L.',
    jobCategory: 'Patient Care',
    experience: '9 Yrs Exp',
    gender: 'Female',
    timing: 'Full Time (Night)',
    salary: '₹30,000',
  },
];

export const TOTAL_PAGES = 5;

const PAGE_IMAGES: Record<number, string[]> = {
  1: ['Anita Pandey.jpg', 'img17.jpg', 'h1.jpg', 'photo (1).jpg', 'img2.jpg', 'img3.jpg'],
  2: ['img25.jpg', 'img22.jpg', 'h2.jpg', 'Chaitali Sharma.jpg', 'Disha Yadav.JPG', 'driver.png', 'Arunachalam.jpg', 'Deepika Ganguly.jpg'],
  3: ['us_andhra_woman_murder.jpg', 'download.jpg', 'Telugu-housemaid-is-readily-available-for-Indian-families-In-United-arab-emirates5206ff18deb51d27d200.jpg', 'images (1).jpg', 'images (2).jpg', 'images (3).jpg', 'images (4).jpg', 'images (5).jpg'],
  4: ['images (6).jpg', 'images (12).jpg', 'images (8).jpg', 'images (9).jpg', 'images (10).jpg', 'images (14).jpg']
};

// Apply real website images based on page and index
EMPLOYEE_PROFILES.forEach((profile) => {
  const images = PAGE_IMAGES[profile.page] || PAGE_IMAGES[profile.page % 4 || 1];
  const pageProfiles = EMPLOYEE_PROFILES.filter(p => p.page === profile.page);
  const indexOnPage = pageProfiles.indexOf(profile);
  const filename = images[indexOnPage % images.length];
  profile.imageFilename = filename;
  profile.imageUrl = `https://www.anydomestichelp.com/images/${encodeURIComponent(filename)}`;
});

export function getProfilesByPage(page: number): EmployeeProfile[] {
  return EMPLOYEE_PROFILES.filter((p) => p.page === page);
}

export function getProfilesCountByPage(page: number): number {
  return EMPLOYEE_PROFILES.filter((p) => p.page === page).length;
}
